# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acharyas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acharya',
            name='admin_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='acharya',
            name='biodata',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='acharya',
            name='br_diksha_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='acharya',
            name='centre',
            field=models.ManyToManyField(blank=True, related_name='acharya', to='acharyas.Centre'),
        ),
        migrations.AlterField(
            model_name='acharya',
            name='dob',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='acharya',
            name='joined_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='acharya',
            name='profile_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='acharya',
            name='salutation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='acharya',
            name='trained_under',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acharyas.Acharya'),
        ),
    ]
