# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acharyas', '0002_auto_20170828_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='acharya',
            name='chinmaya_id',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='acharya',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acharya',
            name='biodata',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acharya',
            name='br_diksha_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acharya',
            name='centre',
            field=models.ManyToManyField(blank=True, null=True, related_name='acharya', to='acharyas.Centre'),
        ),
        migrations.AlterField(
            model_name='acharya',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acharya',
            name='joined_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acharya',
            name='profile_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acharya',
            name='salutation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
