# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acharyas', '0003_auto_20170828_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acharya',
            name='chinmaya_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
