# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acharyas', '0005_auto_20170828_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acharya',
            name='br_diksha_date',
            field=models.DateField(blank=True, null=True, verbose_name='Brahmachari(ni) diksha date'),
        ),
        migrations.AlterField(
            model_name='acharya',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='acharya',
            name='salutation',
            field=models.CharField(choices=[('Brni', 'Brni'), ('Br', 'Br'), ('Swamiji', 'Swamiji'), ('Swamini', 'Swamini')], default='', max_length=100),
        ),
    ]
