# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('acharyas', '0006_auto_20170828_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='acharya',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='acharya',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Brni', 'Brni'), ('Br', 'Br'), ('Swami', 'Swami'), ('Swamini', 'Swamini')], default='', max_length=100),
        ),
    ]
