# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acharyas', '0007_auto_20170828_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='acharya',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
