# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 23:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acharyas', '0011_auto_20170828_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acharya',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
